# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t5N2VA2skZkbREmlcPlGRGLuVaQ9wnxb
"""

import sys
outputTask1 = print(3116)
outputTask1.saveAsTextFile(sys.argv[2])